package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Curso;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class CursoRepositoryDB implements CursoRepository{

    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryDB(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, pass);
    }


    @Override
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS CURSOS (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR(100) NOT NULL,
                activo boolean DEFAULT(true)
                );
                """;

        try {
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);
        } catch (SQLException e) {
            throw new RuntimeException("Error inicializando schema", e);
        }
    }

    @Override
    public void crearCurso(int id, String nombre, Boolean activo) {
        String sql = "INSERT INTO CURSOS(id, nombre, activo) values(?, ? , ?)";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setInt(1, id);
            ps.setString(2, nombre);
            ps.setBoolean(3, activo);

            ps.executeUpdate();

            ResultSet keys = ps.getGeneratedKeys();

        } catch (SQLException e) {
            throw new RuntimeException("Error insertando cursos", e);
        }
    }

    @Override
    public void activar(int id) {
        String sql = "UPDATE CURSOS SET activo=true where id = ?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
        } catch (SQLException e) {
            throw new RuntimeException("Error buscando cursos por id " + id, e);
        }
    }

    @Override
    public void eliminarSiNombreContiene(String nombre) {
        String sql = "DELETE FROM CURSOS WHERE nombre like %?%";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, nombre);
             ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error buscando cursos por nombre " + nombre, e);
        }
    }

    @Override
    public List<Curso> listarPorEstado(boolean activo) {
        String sql = "Select * FROM CURSOS ORDER BY ACTIVO";
        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            List<Curso> out = new ArrayList<>();
            while (rs.next()) {
                out.add(mapCursos(rs));
            }
            return out;

        } catch (SQLException e) {
            throw new RuntimeException("Error listando cursos", e);
        }
    }

    @Override
    public List<Curso> listarOrdenadoPorCampo(String campo, String tipoDeOrden) {
        try {
            if (tipoDeOrden.equalsIgnoreCase("ASCENDENTE")) {
                String sql = "SELECT * FROM CURSOS ORDER BY ? asc";

                Connection c = getConnection();
                PreparedStatement ps = c.prepareStatement(sql);
                ps.setString(1, campo);
                System.out.println(ps);
                ResultSet rs = ps.executeQuery();

                List<Curso> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(mapCursos(rs));
                }
                return out;

            } else if (tipoDeOrden.equalsIgnoreCase("DESCEDENTE")) {
                String sql = "SELECT * FROM CURSOS ORDER BY ? DESC";

                Connection c = getConnection();
                PreparedStatement ps = c.prepareStatement(sql);
                ps.setString(1, campo);
                ResultSet rs = ps.executeQuery();

                List<Curso> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(mapCursos(rs));
                }
                return out;

            }else {
                throw new IllegalArgumentException("MEtodo de ordanaicón no soportado");
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error listando cursos", e);
        }
    }


    private Curso mapCursos(ResultSet rs) throws SQLException {
        return new Curso(
                rs.getInt("id"),
                rs.getString("nombre"),
                rs.getBoolean("activo")
        );
    }
}
